import type { Metadata } from "next";
import {  Montserrat, Averia_Serif_Libre } from "next/font/google";
import "./globals.css";
import { useLocale } from "next-intl";
import Sidebar from "@/components/layout/Sidebar";

const  montserrat =  Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = useLocale();
  return (
    <html lang={locale}>
      <body className={ montserrat.className}>
        <div className="flex gap-1">
          <div className="w-[15%]">
            <Sidebar />
          </div>
          <div className="bg-blue-200 w-[85%]">{children}</div>
        </div>
      </body>
    </html>
  );
}
